openapi: 3.0.1
info:
  title: Quote Plugin
  description: Fetches a Motivational Quote 
  version: 'v1'
servers:
  - url: http://localhost:81
paths:
  /:
    get:
     responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getQuoteResponse'
components:
  schemas:
    getQuoteResponse:
      type: string
        description: The quote
  